server:
    port: 8090

spring:
    application:
        name: board
    datasource:
        password: spring1234
        url: jdbc:mariadb://localhost:3306/board
        username: test
    thymeleaf:
        cache: false

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect
        show-sql: true

mybatis:
    mapper-locations: classpath:mapper/boardmapper.xml